version: "{build}"

branches:
  only:
    - master
    - /^greenkeeper/.*$/

environment:
  nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm cache clean
  - npm install

test_script:
  - npm run unit-test

build: off
